
DO (
  IN USERNAME NVARCHAR(255) => ?,
  IN USERPASS NVARCHAR(255) => ?,
  IN SCHEMANAME NVARCHAR(255) => ?,
  IN CREATEGROUP BOOLEAN => ?
)
BEGIN SEQUENTIAL EXECUTION
  DECLARE CONTAINER_GROUP_EXISTS INT;
  DECLARE OPERATOR_ROLE NVARCHAR(256);
  DECLARE RETURN_CODE INT;
  DECLARE REQUEST_ID BIGINT;
  DECLARE ALL_MESSAGES _SYS_DI.TT_MESSAGES;
  DECLARE MESSAGES _SYS_DI.TT_MESSAGES;
  DECLARE PRIVILEGES _SYS_DI.TT_API_PRIVILEGES;
  DECLARE SCHEMA_PRIV _SYS_DI.TT_SCHEMA_PRIVILEGES;

  DECLARE IGNOREPARAMS _SYS_DI.TT_PARAMETERS;

  NO_PARAMS = SELECT * FROM _SYS_DI.T_NO_PARAMETERS;

  SELECT NAME INTO OPERATOR_ROLE FROM SYS.PRIVILEGES WHERE NAME = 'OPERATOR' OR NAME = 'USERGROUP OPERATOR';
  IF :CREATEGROUP = FALSE THEN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN END;
    CALL _SYS_DI.DROP_CONTAINER_GROUP(:SCHEMANAME, :NO_PARAMS, :RETURN_CODE, :REQUEST_ID, :MESSAGES);
    COMMIT;
    ALL_MESSAGES = SELECT * FROM :MESSAGES;

    EXEC 'DROP USER ' || :USERNAME || ' CASCADE';
  END IF;

  IF :CREATEGROUP = TRUE THEN
    BEGIN
      DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN END; -- try catch
      EXEC 'CREATE USERGROUP "' || :SCHEMANAME || '_USERS"';
    END;
    BEGIN
      DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN END; -- try catch
      EXEC 'CREATE USER ' || :USERNAME || ' PASSWORD ' || :USERPASS || ' NO FORCE_FIRST_PASSWORD_CHANGE SET USERGROUP "' || :SCHEMANAME || '_USERS"';
      EXEC 'ALTER USER ' || :USERNAME || ' DISABLE PASSWORD LIFETIME';
      EXEC 'GRANT ' || :OPERATOR_ROLE || ' ON USERGROUP "' || :SCHEMANAME || '_USERS" TO ' || :USERNAME;
      EXEC 'GRANT EXECUTE ON SYS.GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS TO ' || :USERNAME || ' WITH GRANT OPTION';
      EXEC 'GRANT OPTIMIZER ADMIN TO ' || :USERNAME || ' WITH ADMIN OPTION';
    END;

    SELECT COUNT(*) INTO CONTAINER_GROUP_EXISTS FROM _SYS_DI.M_ALL_CONTAINER_GROUPS WHERE CONTAINER_GROUP_NAME = :SCHEMANAME;
    IF :CONTAINER_GROUP_EXISTS = 0 THEN
      CALL _SYS_DI.CREATE_CONTAINER_GROUP(:SCHEMANAME, :NO_PARAMS, :RETURN_CODE, :REQUEST_ID, :MESSAGES);
      COMMIT;
      ALL_MESSAGES = SELECT * FROM :MESSAGES;

      PRIVILEGES = SELECT PRIVILEGE_NAME, OBJECT_NAME, PRINCIPAL_SCHEMA_NAME, :USERNAME AS PRINCIPAL_NAME FROM _SYS_DI.T_DEFAULT_CONTAINER_GROUP_ADMIN_PRIVILEGES;
      CALL _SYS_DI.GRANT_CONTAINER_GROUP_API_PRIVILEGES(:SCHEMANAME, :PRIVILEGES, :NO_PARAMS, :RETURN_CODE, :REQUEST_ID, :MESSAGES);
      COMMIT;
      ALL_MESSAGES = SELECT * FROM :ALL_MESSAGES UNION ALL SELECT * FROM :MESSAGES;
    END IF;
    SELECT * FROM :ALL_MESSAGES;
  END IF;
  COMMIT;
END;
