DO
BEGIN
  DECLARE userName NVARCHAR(100);

  -- Define HDI return types
  DECLARE RETURN_CODE int;
  DECLARE REQUEST_ID bigint;
  DECLARE MESSAGES _SYS_DI.TT_MESSAGES;
  DECLARE DIFF _SYS_DI.TT_FILESFOLDERS_STATUS;

  -- Define HDI input types
  DECLARE FILES _SYS_DI.TT_FILESFOLDERS_CONTENT;
  DECLARE DEPLOY _SYS_DI.TT_FILESFOLDERS;
  DECLARE UNDEPLOY _SYS_DI.TT_FILESFOLDERS;
  DECLARE FILES_PARAMS _SYS_DI.TT_FILESFOLDERS_PARAMETERS;

  NO_PARAMS = SELECT * FROM _SYS_DI.T_NO_PARAMETERS;

  FILES = SELECT * FROM JSON_TABLE('{{{JSON_FILES}}}', '$[*]' COLUMNS (
    PATH NVARCHAR(511) PATH '$.path',
    CONTENT NVARCHAR(2147483647) PATH '$.content'
  ));
  CALL {{{CONTAINER_NAME}}}#DI.WRITE(:FILES, :NO_PARAMS, :RETURN_CODE, :REQUEST_ID, :MESSAGES);

  DEPLOY = SELECT PATH FROM :FILES;
  CALL {{{CONTAINER_NAME}}}#DI.STATUS(:DEPLOY, :NO_PARAMS, :RETURN_CODE, :REQUEST_ID, :MESSAGES, :DIFF);
  -- SELECT * FROM :DIFF; -- Return the changed files

  CALL {{{CONTAINER_NAME}}}#DI.MAKE(:DEPLOY, :UNDEPLOY, :FILES_PARAMS, :NO_PARAMS, :RETURN_CODE, :REQUEST_ID, :MESSAGES);
  -- SELECT * FROM :MESSAGES; -- Return the make log messages
END;
