#!/bin/bash
# Resolve repo paths so the script can be invoked from anywhere.
HCE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
HANA_DIR="$(cd -- "$HCE_DIR/../.." && pwd)"

write_env_file() {
  local env_file="$HANA_DIR/.env"
  cat > "$env_file" <<'EOF'
# Auto-generated by hana/tools/hce/start.sh — telemetry pointing at local Jaeger
SAP_PASSPORT=true
CDS_REQUIRES_TELEMETRY_KIND=telemetry-to-jaeger
EOF
  echo "wrote telemetry env vars to $env_file"
}

cd "$HCE_DIR"
exists=$(docker images hana-master:current -q);
if [ $exists ]; then
  docker compose up -d;
  ./ready.sh;
  write_env_file
  echo "Jaeger UI: http://localhost:16686"
else
  ./update.sh;
  if [ $? -ne 0 ]; then
    echo "hana image not found";
    exit 1;
  fi
  ./start.sh "$@";
fi

