require('./search.test')
// require('./read.test')
// require('./insert.test')
// require('./delete.test')
// require('./update.test')
// require('./funcs.test')
// require('./orderBy.test')
// require('./genres.test')
// require('./localization.test')
