namespace basic.projection;

using {basic.literals} from './literals';

entity globals  as projection on literals.globals;
entity number   as projection on literals.number;
entity string   as projection on literals.string;
entity date     as projection on literals.date;
entity time     as projection on literals.time;
entity dateTime as projection on literals.dateTime;

entity now_in_view as select $now as now from literals.globals;

entity ![all]   as
    select from literals.globals {
      bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
      // NULL as vector : Vector,
    }
  union all
    select from literals.uuid {
      cast(null as Boolean) as bool,
      uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.number {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      integer8,
      integer16,
      integer32,
      integer64,
      double,
      float,
      decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.string {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      string,
      char,
      short,
      medium,
      large,
      blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.date {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }

  union all
    select from literals.time {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.dateTime {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.timestamp {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.array {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      string  as stringArray,
      integer as integerArray,
      cast(null as Binary) as binary,
      cast(null as LargeBinary) as largebinary,
    // NULL as vector : Vector,
    }
  union all
    select from literals.binaries {
      cast(null as Boolean) as bool,
      cast(null as UUID) as uuid,
      cast(null as UInt8) as integer8,
      cast(null as Int16) as integer16,
      cast(null as Int32) as integer32,
      cast(null as Int64) as integer64,
      cast(null as cds.Double) as double,
      cast(null as  cds.Decimal) as float,
      cast(null as cds.Decimal(5, 4)) as decimal,
      cast(null as String) as string,
      cast(null as String(1)) as char,
      cast(null as  String(10)) as short,
      cast(null as String(100)) as medium,
      cast(null as String(5000)) as large,
      cast(null as LargeString) as blob,
      cast(null as Date) as date,
      cast(null as Time) as time,
      cast(null as DateTime) as dateTime,
      cast(null as Timestamp) as timestamp,
      cast(null as LargeString) as stringArray,
      cast(null as LargeString) as integerArray,
      binary,
      largebinary,
    // NULL as vector : Vector,
    };
