const enabled = process.stdout.isTTY && !process.env.NO_COLOR || process.env.FORCE_COLOR
const color = enabled ? ttl => ttl[0] : ()=>''

module.exports = {
  enabled,
  RESET:          color `\x1b[0m`,
  BOLD:           color `\x1b[1m`,
  BRIGHT:         color `\x1b[1m`,
  DIMMED:         color `\x1b[2m`,
  ITALIC:         color `\x1b[3m`,
  UNDER:          color `\x1b[4m`,
  BLINK:          color `\x1b[5m`,
  FLASH:          color `\x1b[6m`,
  INVERT:         color `\x1b[7m`,
  BLACK:          color `\x1b[30m`,
  RED:            color `\x1b[31m`,
  GREEN:          color `\x1b[32m`,
  YELLOW:         color `\x1b[33m`,
  BLUE:           color `\x1b[34m`,
  PINK:           color `\x1b[35m`,
  CYAN:           color `\x1b[36m`,
  LIGHT_GRAY:     color `\x1b[37m`,
  DEFAULT:        color `\x1b[39m`,
  GRAY:           color `\x1b[90m`,
  LIGHT_RED:      color `\x1b[91m`,
  LIGHT_GREEN:    color `\x1b[92m`,
  LIGHT_YELLOW:   color `\x1b[93m`,
  LIGHT_BLUE:     color `\x1b[94m`,
  LIGHT_PINK:     color `\x1b[95m`,
  LIGHT_CYAN:     color `\x1b[96m`,
  WHITE:          color `\x1b[97m`,
  bg: {
    BLACK:        color `\x1b[40m`,
    RED:          color `\x1b[41m`,
    GREEN:        color `\x1b[42m`,
    YELLOW:       color `\x1b[43m`,
    BLUE:         color `\x1b[44m`,
    PINK:         color `\x1b[45m`,
    CYAN:         color `\x1b[46m`,
    WHITE:        color `\x1b[47m`,
    DEFAULT:      color `\x1b[49m`,
    LIGHT_GRAY:   color `\x1b[100m`,
    LIGHT_RED:    color `\x1b[101m`,
    LIGHT_GREEN:  color `\x1b[102m`,
    LIGHT_YELLOW: color `\x1b[103m`,
    LIGHT_BLUE:   color `\x1b[104m`,
    LIGHT_PINK:   color `\x1b[105m`,
    LIGHT_CYAN:   color `\x1b[106m`,
    LIGHT_WHITE:  color `\x1b[107m`,
  },
}
