on:
  push:
    branches:
      - update/releases
name: release-please
jobs:
  release-please:
    permissions:
        contents: read
        pull-requests: write
        packages: write
        id-token: write
    runs-on: ubuntu-latest
    environment: npm
    steps:
      # v4.4.0
      # The logic below handles the npm publication:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      ## debug info
      - run: node config.mjs 
