on:
  push:
    branches:
      - ghadev
name: release-please
jobs:
  release-please:
    permissions:
        contents: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{secrets.CDS_DBS_TOKEN}}
          command: manifest
          monorepo-tags: true
      - name: log
        run: echo "${{ steps.release.outputs.releases_created }}"
      - name: Only run subsquent steps if a release needs to be published
        run: |
          if ["${{ steps.release.outputs.releases_created }}" === ""]; then
            echo "OK proceeding to release"
          else
            echo "No release needs to be published, exiting…"
            return
          fi
