name: Tests WASM

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, auto_merge_enabled]

# Allow parallel jobs on `main`, so that each commit is tested. For PRs, run only the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Node.js ${{ matrix.node }}

    strategy:
      fail-fast: true
      matrix:
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci
      # Remove better-sqlite3 to force switching to sql.js
      - run: npm install sql.js && rm -rf node_modules/better-sqlite3/
      - run: npm test -w sqlite -- --maxWorkers=1
        env:
          FORCE_COLOR: true
